// ブラウザで入力すると本来の機能が実行されるショートカットキー
export const DENY_LIST_OF_KEY_COMBINATION = [
  {
    altKey: false,
    ctrlKey: true,
    metaKey: false,
    shiftKey: false,
    key: 'F2',
  },
  {
    altKey: false,
    ctrlKey: true,
    metaKey: false,
    shiftKey: false,
    key: 'F5',
  },
  {
    altKey: true,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    key: 'd',
  },
  {
    altKey: false,
    ctrlKey: true,
    metaKey: true,
    shiftKey: false,
    key: 'd',
  },
  {
    altKey: false,
    ctrlKey: false,
    metaKey: true,
    shiftKey: true,
    key: 'q',
  },
  {
    altKey: false,
    ctrlKey: true,
    metaKey: true,
    shiftKey: false,
    key: 'q',
  },
  {
    altKey: true,
    ctrlKey: false,
    metaKey: true,
    shiftKey: true,
    key: 'q',
  },
  {
    altKey: false,
    ctrlKey: false,
    metaKey: true,
    shiftKey: true,
    key: '5',
  },
  {
    altKey: false,
    ctrlKey: false,
    metaKey: true,
    shiftKey: true,
    key: '4',
  },
  {
    altKey: false,
    ctrlKey: false,
    metaKey: true,
    shiftKey: true,
    key: '3',
  },
  {
    altKey: false,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    key: 'Space',
  },
  {
    altKey: false,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    key: 'Tab',
  },
  {
    altKey: true,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    key: 'Escape',
  },
  {
    altKey: false,
    ctrlKey: true,
    metaKey: false,
    shiftKey: false,
    key: 'ArrowDown',
  },
] as const

export const KEY_COMBINATIONS_ONLY_AVAILABLE_IN_FULL_SCREEN_MODE = [
  {
    altKey: false,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    key: 'n',
  },
  {
    altKey: false,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    key: 't',
  },
  {
    altKey: false,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    key: 'w',
  },
  {
    altKey: false,
    ctrlKey: false,
    metaKey: true,
    shiftKey: true,
    key: 'n',
  },
  {
    altKey: false,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    key: 'q',
  },
  {
    altKey: false,
    ctrlKey: false,
    metaKey: true,
    shiftKey: true,
    key: 't',
  },
  {
    altKey: false,
    ctrlKey: false,
    metaKey: true,
    shiftKey: true,
    key: 'w',
  },
  {
    altKey: false,
    ctrlKey: true,
    metaKey: false,
    shiftKey: false,
    key: 'Tab',
  },
  {
    altKey: false,
    ctrlKey: true,
    metaKey: false,
    shiftKey: true,
    key: 'Tab',
  },
  {
    altKey: true,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    key: 'ArrowLeft',
  },
  {
    altKey: true,
    ctrlKey: false,
    metaKey: true,
    shiftKey: false,
    key: 'ArrowRight',
  },
  {
    altKey: true,
    ctrlKey: false,
    metaKey: false,
    shiftKey: true,
    key: 'ArrowDown',
  },
] as const
