// Reference: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values
const standardKeys = [
  'Unidentified',
  'Alt',
  'AltGraph',
  'CapsLock',
  'Control',
  'Fn',
  'FnLock',
  'Hyper',
  'Meta',
  'NumLock',
  'ScrollLock',
  'Shift',
  'Super',
  'Symbol',
  'SymbolLock',
  'Enter',
  'Tab',
  ' ',
  'ArrowDown',
  'ArrowLeft',
  'ArrowRight',
  'ArrowUp',
  'End',
  'Home',
  'PageDown',
  'PageUp',
  'Backspace',
  'Clear',
  'Copy',
  'CrSel',
  'Cut',
  'Delete',
  'EraseEof',
  'ExSel',
  'Insert',
  'Paste',
  'Redo',
  'Undo',
  'Accept',
  'Again',
  'Attn',
  'Cancel',
  'ContextMenu',
  'Escape',
  'Execute',
  'Find',
  'Finish',
  'Help',
  'Pause',
  'Play',
  'Props',
  'Select',
  'ZoomIn',
  'ZoomOut',
  'BrightnessDown',
  'BrightnessUp',
  'Eject',
  'LogOff',
  'Power',
  'PowerOff',
  'PrintScreen',
  'Hibernate',
  'Standby',
  'WakeUp',
  'AllCandidates',
  'Alphanumeric',
  'CodeInput',
  'Compose',
  'Convert',
  'Dead',
  'FinalMode',
  'GroupFirst',
  'GroupLast',
  'GroupNext',
  'GroupPrevious',
  'ModeChange',
  'NextCandidate',
  'NonConvert',
  'PreviousCandidate',
  'Process',
  'SingleCandidate',
  'HangulMode',
  'HanjaMode',
  'JunjaMode',
  'Eisu',
  'Hankaku',
  'Hiragana',
  'HiraganaKatakana',
  'KanaMode',
  'KanjiMode',
  'Katakana',
  'Romaji',
  'Zenkaku',
  'ZenkakuHanaku',
  '`', // GDK_KEY_dead_grave
  '´', // GDK_KEY_dead_acute
  'ˆ', // GDK_KEY_dead_circumflex
  '˜', // GDK_KEY_dead_tilde
  '͂', // GDK_KEY_dead_perispomeni
  '¯', // GDK_KEY_dead_macron
  '˘', // GDK_KEY_dead_breve
  '˙', // GDK_KEY_dead_abovedot
  '¨', // GDK_KEY_dead_diaeresis
  '˚', // GDK_KEY_dead_abovering
  '˝', // GDK_KEY_dead_doubleacute
  'ˇ', // GDK_KEY_dead_caron
  '¸', // GDK_KEY_dead_cedilla
  '˛', // GDK_KEY_dead_ogonek
  'ͅ', // GDK_KEY_dead_iota
  '゙', // GDK_KEY_dead_voiced_sound
  '゚', // GDK_KEY_dead_semivoiced_sound
  '̣̣', // GDK_KEY_dead_belowdot
  '̡', // GDK_KEY_dead_hook
  '̛', // GDK_KEY_dead_horn
  '̶̶', // GDK_KEY_dead_stroke
  '̓̓', // GDK_KEY_dead_abovecomma
  '᾿', // GDK_KEY_dead_psili
  'ʽ', // GDK_KEY_dead_abovereversedcomma
  '῾', // GDK_KEY_dead_dasia
  '̏', // GDK_KEY_dead_doublegrave
  '˳', // GDK_KEY_dead_belowring
  '̱', // GDK_KEY_dead_belowmacron
  'ꞈ', // GDK_KEY_dead_belowcircumflex
  '̰', // GDK_KEY_dead_belowtilde
  '̮', // GDK_KEY_dead_belowbreve
  '̤', // GDK_KEY_dead_belowdiaeresis
  '̯', // GDK_KEY_dead_invertedbreve
  '̦', // GDK_KEY_dead_belowcomma
  'F1',
  'F2',
  'F3',
  'F4',
  'F5',
  'F6',
  'F7',
  'F8',
  'F9',
  'F10',
  'F11',
  'F12',
  'F13',
  'F14',
  'F15',
  'F16',
  'F17',
  'F18',
  'F19',
  'F20',
  'Soft1',
  'Soft2',
  'Soft3',
  'Soft4',
  'AppSwitch',
  'Call',
  'Camera',
  'CameraFocus',
  'EndCall',
  'GoBack',
  'GoHome',
  'HeadsetHook',
  'LastNumberRedial',
  'Notification',
  'MannerMode',
  'VoiceDial',
  'ChannelDown',
  'ChannelUp',
  'MediaFastForward',
  'MediaPause',
  'MediaPlay',
  'MediaPlayPause',
  'MediaRecord',
  'MediaRewind',
  'MediaStop',
  'MediaTrackNext',
  'MediaTrackPrevious',
  'AudioBalanceLeft',
  'AudioBalanceRight',
  'AudioBassDown',
  'AudioBassBoostDown',
  'AudioBassBoostToggle',
  'AudioBassBoostUp',
  'AudioBassUp',
  'AudioFaderFront',
  'AudioFaderRear',
  'AudioSurroundModeNext',
  'AudioTrebleDown',
  'AudioTrebleUp',
  'AudioVolumeDown',
  'AudioVolumeMute',
  'AudioVolumeUp',
  'MicrophoneToggle',
  'MicrophoneVolumeDown',
  'MicrophoneVolumeMute',
  'MicrophoneVolumeUp',
  'TV',
  'TV3DMode',
  'TVAntennaCable',
  'TVAudioDescription',
  'TVAudioDescriptionMixDown',
  'TVAudioDescriptionMixUp',
  'TVContentsMenu',
  'TVDataService',
  'TVInput',
  'TVInputComponent1',
  'TVInputComponent2',
  'TVInputComposite1',
  'TVInputComposite2',
  'TVInputHDMI1',
  'TVInputHDMI2',
  'TVInputHDMI3',
  'TVInputHDMI4',
  'TVInputVGA1',
  'TVMediaContext',
  'TVNetwork',
  'TVNumberEntry',
  'TVPower',
  'TVRadioService',
  'TVSatellite',
  'TVSatelliteBS',
  'TVSatelliteCS',
  'TVSatelliteToggle',
  'TVTerrestrialAnalog',
  'TVTerrestrialDigital',
  'TVTimer',
  'AVRInput',
  'AVRPower',
  'ColorF0Red',
  'ColorF1Green',
  'ColorF2Yellow',
  'ColorF3Blue',
  'ColorF4Grey',
  'ColorF5Brown',
  'ClosedCaptionToggle',
  'Dimmer',
  'DisplaySwap',
  'DVR',
  'Exit',
  'FavoriteClear0',
  'FavoriteClear1',
  'FavoriteClear2',
  'FavoriteClear3',
  'FavoriteRecall0',
  'FavoriteRecall1',
  'FavoriteRecall2',
  'FavoriteRecall3',
  'FavoriteStore0',
  'FavoriteStore1',
  'FavoriteStore2',
  'FavoriteStore3',
  'Guide',
  'GuideNextDay',
  'GuidePreviousDay',
  'Info',
  'InstantReplay',
  'Link',
  'ListProgram',
  'LiveContent',
  'Lock',
  'MediaApps',
  'MediaAudioTrack',
  'MediaLast',
  'MediaSkipBackward',
  'MediaSkipForward',
  'MediaStepBackward',
  'MediaStepForward',
  'MediaTopMenu',
  'NavigateIn',
  'NavigateNext',
  'NavigateOut',
  'NavigatePrevious',
  'NextFavoriteChannel',
  'NextUserProfile',
  'OnDemand',
  'Pairing',
  'PinPDown',
  'PinPMove',
  'PinPToggle',
  'PinPUp',
  'PlaySpeedDown',
  'PlaySpeedReset',
  'PlaySpeedUp',
  'RandomToggle',
  'RcLowBattery',
  'RecordSpeedNext',
  'RfBypass',
  'ScanChannelsToggle',
  'ScreenModeNext',
  'Settings',
  'SplitScreenToggle',
  'STBInput',
  'STBPower',
  'Subtitle',
  'Teletext',
  'VideoModeNext',
  'Wink',
  'ZoomToggle',
  'SpeechCorrectionList',
  'SpeechInputToggle',
  'Close',
  'New',
  'Open',
  'Print',
  'Save',
  'SpellCheck',
  'MailForward',
  'MailReply',
  'MailSend',
  'LaunchCalculator',
  'LaunchCalendar',
  'LaunchContacts',
  'LaunchMail',
  'LaunchMediaPlayer',
  'LaunchMusicPlayer',
  'LaunchMyComputer',
  'LaunchPhone',
  'LaunchScreenSaver',
  'LaunchSpreadsheet',
  'LaunchWebBrowser',
  'LaunchWebCam',
  'LaunchWordProcessor',
  'LaunchApplication1',
  'LaunchApplication2',
  'LaunchApplication3',
  'LaunchApplication4',
  'LaunchApplication5',
  'LaunchApplication6',
  'LaunchApplication7',
  'LaunchApplication8',
  'LaunchApplication9',
  'LaunchApplication10',
  'LaunchApplication11',
  'LaunchApplication12',
  'LaunchApplication13',
  'LaunchApplication14',
  'LaunchApplication15',
  'LaunchApplication16',
  'BrowserBack',
  'BrowserFavorites',
  'BrowserForward',
  'BrowserHome',
  'BrowserRefresh',
  'BrowserSearch',
  'BrowserStop',
  'Decimal',
  'Key11',
  'Key12',
  'Multiply',
  'Add',
  'Clear',
  'Divide',
  'Subtract',
  'Separator',
  '[0-9]',
  '[a-z]',
]
const STANDARD_KEY_REGEXP = new RegExp(standardKeys.join('|'))

const modifiedKeys = ['\\.', '\\?', '\\\\', '`', '˜', 'Plus'] // Plus は + のこと。説明文と区別をつけるため、あえて plus として扱っている
export const MODIFIED_KEY_REGEXP = new RegExp(modifiedKeys.join('|'))

const additionalKeys = ['plus'] // 説明文中の単語と区別するため、本来の key と別名にした
const ADDITIONAL_KEY_REGEXP = new RegExp(additionalKeys.join('|'))

const missingKeys = ['\\[', '\\]'] // key として存在するけれど MDN には載っていない
const MISSING_KEY_REGEXP = new RegExp(missingKeys.join('|'))

const KEY_REGEXP = new RegExp(
  '^(' +
    STANDARD_KEY_REGEXP.source +
    '|' +
    MODIFIED_KEY_REGEXP.source +
    '|' +
    ADDITIONAL_KEY_REGEXP.source +
    '|' +
    MISSING_KEY_REGEXP.source +
    ')$',
  'i'
)
export default KEY_REGEXP
