const keyToSymbolArray = [
  ['Alt', '⌥'], // macOS
  ['ArrowDown', '↓'],
  ['ArrowLeft', '←'],
  ['ArrowRight', '→'],
  ['ArrowUp', '↑'],
  ['Backspace', '⌫'], // macOS では Delete
  ['CapsLock', '⇪'],
  ['Control', '⌃'],
  ['Delete', '⌦'], // macOS では Forward Delete
  ['Enter', '↩'],
  ['Escape', '⎋'],
  ['Meta', '⌘'], // macOS
  ['PageUp', '⇞'],
  ['PageDown', '⇟'],
  ['Plus', '+'],
  ['NumpadAdd', '+'],
  ['NumpadDecimal', '.'],
  ['NumpadDivide', '/'],
  ['NumpadMultiply', '*'],
  ['NumpadSubtract', '-'],
  ['Shift', '⇧'],
  ['grave', '`'],
  ['acute', '´'],
  ['circumflex', 'ˆ'],
  ['tilde', '˜'],
  ['perispomeni', '͂'],
  ['macron', '¯'],
  ['breve', '˘'],
  ['abovedot', '˙'],
  ['diaeresis', '¨'],
  ['abovering', '˚'],
  ['doubleacute', '˝'],
  ['caron', 'ˇ'],
  ['cedilla', '¸'],
  ['ogonek', '˛'],
  ['iota', 'ͅ'],
  ['voiced_sound', '゙'],
  ['semivoiced_sound', '゚'],
  ['belowdot', '̣̣'],
  ['hook', '̡'],
  ['horn', '̛'],
  ['stroke', '̶̶'],
  ['abovecomma', '̓̓'],
  ['psili', '᾿'],
  ['abovereversedcomma', 'ʽ'],
  ['dasia', '῾'],
  ['doublegrave', '̏'],
  ['belowring', '˳'],
  ['belowmacron', '̱'],
  ['belowcircumflex', 'ꞈ'],
  ['belowtilde', '̰'],
  ['belowbreve', '̮'],
  ['belowdiaeresis', '̤'],
  ['invertedbreve', '̯'],
  ['belowcomma', '̦'],
] as const

export default keyToSymbolArray
