// 「KeyboardLayoutMap.get(KeyboardEvent.code) の返り値が undefined となる KeyboardEvent.code」 と KeyboardEvent.key の対応
const specialCodeToKeyArray = [
  ['AltLeft', 'Alt'],
  ['AltRight', 'Alt'],
  ['ArrowDown', 'ArrowDown'],
  ['ArrowLeft', 'ArrowLeft'],
  ['ArrowRight', 'ArrowRight'],
  ['ArrowUp', 'ArrowUp'],
  ['Backspace', 'Backspace'],
  ['CapsLock', 'CapsLock'],
  ['ContextMenu', 'ContextMenu'],
  ['ControlLeft', 'Control'],
  ['ControlRight', 'Control'],
  ['Delete', 'Delete'],
  ['End', 'End'],
  ['Enter', 'Enter'],
  ['Escape', 'Escape'],
  ['F1', 'F1'],
  ['F10', 'F10'],
  ['F11', 'F11'],
  ['F12', 'F12'],
  ['F13', 'F13'],
  ['F2', 'F2'],
  ['F3', 'F3'],
  ['F4', 'F4'],
  ['F5', 'F5'],
  ['F6', 'F6'],
  ['F7', 'F7'],
  ['F8', 'F8'],
  ['F9', 'F9'],
  ['Home', 'Home'],
  ['Insert', 'Help'], // macOS で確認した。キーボードによって変わるかも？
  ['Lang1', 'KanjiMode'],
  ['Lang2', 'Eisu'],
  ['MetaLeft', 'Meta'],
  ['MetaRight', 'Meta'],
  ['NumLock', 'Clear'], // macOS で確認した。キーボードによって変わるかも？
  ['Numpad0', '0'],
  ['Numpad1', '1'],
  ['Numpad2', '2'],
  ['Numpad3', '3'],
  ['Numpad4', '4'],
  ['Numpad5', '5'],
  ['Numpad6', '6'],
  ['Numpad7', '7'],
  ['Numpad8', '8'],
  ['Numpad9', '9'],
  ['NumpadAdd', 'NumpadAdd'],
  ['NumpadDecimal', 'NumpadDecimal'],
  ['NumpadDivide', 'NumpadDivide'],
  ['NumpadEnter', 'Enter'],
  ['NumpadMultiply', 'NumpadMultiply'],
  ['NumpadSubtract', 'NumpadSubtract'],
  ['PageDown', 'PageDown'],
  ['PageUp', 'PageUp'],
  ['ShiftLeft', 'Shift'],
  ['ShiftRight', 'Shift'],
  ['Space', 'Space'], // 正しくは ['Space', ' '] だが、空白では表示されているか判別つかないため Space とした
  ['Tab', 'Tab'],
] as const // https://stackoverflow.com/questions/67631458/no-overload-matches-this-call-while-constructing-map-from-array

export default specialCodeToKeyArray
